services:
  - name: rafi-mentor-server
    type: web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    rootDir: server
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://rafigabizon11:300495Rg%24@cluster0.w3s2o.mongodb.net/code-mentor?retryWrites=true&w=majority

  - name: rafi-mentor-client
    type: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    rootDir: client
    envVars:
      - key: REACT_APP_API_URL
        value: https://rafi-mentor-server.onrender.com
      - key: REACT_APP_SOCKET_URL
        value: https://rafi-mentor-server.onrender.com
