services:
  - name: my-node-server
    type: web
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server/index.js"
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
