services:
  - name: rafi-mentor-server
    type: web
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: node index.js
    workingDir: server
    envVars:
      - fromDotEnv: true

  - name: rafi-mentor-client
    type: web
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    envVars:
      - fromDotEnv: true
